### ISSUE TITLE
Database present on git

### ISSUE THREAD

**Issue by arslansmajevic** [mpetojevic/sepm-2023w#1]
Database should, rather created on every java -Dspring.profiles.active=datagen -jar target/e01234567-0.0.1-SNAPSHOT.jar

![image](https://github.com/mpetojevic/sepm-2023w/assets/100355983/2ab9e980-228c-46c8-a5b1-f16d1afed40b)

.db

**Comment by mpetojevic** [comment]
ma daj mars nego mi reci sto mi ne radi
